name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *" 

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Clean pytest cache
        run: rm -rf .pytest_cache reports/

      - name: Run tests
        run: PYTHONPATH=$PYTHONPATH:$(pwd) pytest --html=reports/report.html --self-contained-html

      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: reports/report.html